// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"WeDrive/internal/api"
	"WeDrive/internal/oss"
	"WeDrive/internal/ratelimit"
	"WeDrive/internal/repository"
	"WeDrive/internal/router"
	"WeDrive/internal/service"
	"github.com/gin-gonic/gin"
	"github.com/minio/minio-go/v7"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func BuildApp(db *gorm.DB, redis2 *redis.Client, minio2 *minio.Client) *gin.Engine {
	userRepo := repository.NewUserRepo(db)
	userCacheRepo := repository.NewUserCacheRepo(redis2)
	userService := service.NewUserService(userRepo, userCacheRepo)
	userHandler := api.NewUserHandler(userService)
	fileRepo := repository.NewFileRepo(db)
	uploadCacheRepo := repository.NewUploadCacheRepo(redis2)
	rateLimiter := ratelimit.NewLimiter(redis2)
	storage := oss.NewStorage(minio2)
	fileService := service.NewFileService(fileRepo, uploadCacheRepo, rateLimiter, userRepo, storage, db)
	fileHandler := api.NewFileHandler(fileService)
	shareRepo := repository.NewShareRepo(db)
	shareService := service.NewShareService(shareRepo, fileRepo, storage)
	shareHandler := api.NewShareHandler(shareService)
	engine := router.NewRouter(userHandler, fileHandler, shareHandler)
	return engine
}
