// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"WeDrive/internal/api"
	"WeDrive/internal/cacheguard"
	"WeDrive/internal/mq"
	"WeDrive/internal/oss"
	"WeDrive/internal/ratelimit"
	"WeDrive/internal/repository"
	"WeDrive/internal/router"
	"WeDrive/internal/service"
	"github.com/gin-gonic/gin"
	"github.com/minio/minio-go/v7"
	amqp "github.com/rabbitmq/amqp091-go"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func BuildApp(db *gorm.DB, redis2 *redis.Client, minio2 *minio.Client, mqConn *amqp.Connection) *gin.Engine {
	redisGuard := cacheguard.NewRedisGuard()
	userRepo := repository.NewUserRepo(db)
	userCacheRepo := repository.NewUserCacheRepo(redis2, redisGuard)
	cacheInvalidationPublisher := mq.NewCacheInvalidationPublisher(mqConn)
	userService := service.NewUserService(userRepo, userCacheRepo, cacheInvalidationPublisher)
	userHandler := api.NewUserHandler(userService)
	fileRepo := repository.NewFileRepo(db)
	fileCacheRepo := repository.NewFileCacheRepo(redis2, redisGuard)
	uploadCacheRepo := repository.NewUploadCacheRepo(redis2, redisGuard)
	rateLimiter := ratelimit.NewLimiter(redis2, redisGuard)
	storage := oss.NewStorage(minio2)
	uploadVerificationPublisher := mq.NewUploadVerificationPublisher(mqConn)
	fileService := service.NewFileService(fileRepo, fileCacheRepo, uploadCacheRepo, rateLimiter, userRepo, userCacheRepo, storage, db, cacheInvalidationPublisher, uploadVerificationPublisher)
	fileHandler := api.NewFileHandler(fileService)
	shareRepo := repository.NewShareRepo(db)
	shareCacheRepo := repository.NewShareCacheRepo(redis2, redisGuard)
	shareService := service.NewShareService(shareRepo, shareCacheRepo, fileRepo, rateLimiter, storage)
	shareHandler := api.NewShareHandler(shareService)
	engine := router.NewRouter(userHandler, fileHandler, shareHandler)
	return engine
}
